### ISSUE TITLE
Change the "ng" prefix to something else

### ISSUE THREAD

**Issue by mkhanal** [darul75/ng-slider#15]
'ng' is reserved for official angular components. I stumbled upon this assuming it is from angular team. While I still would use it, I would like it to have some other prefix and not 'ng'

**Comment by kanagukrs** [comment]
my suggestion would be awesome-range-slider or ar-slider (ar - awesome range)

**Comment by darul75** [comment]
I like @kanagukrs your suggestions, I will do it soon, it sounds great and awesome ;)

**Comment by kanagukrs** [comment]
It would be fine if you change the directive name from slider to angular-awesome-slider, right now, you only changed the module and file names

**Comment by darul75** [comment]
ok, I hesitate as it was a bit long name, I will do
