### ISSUE TITLE
no method 'offset'

### ISSUE THREAD

**Issue by miculprogramator** [darul75/ng-slider#42]
what dependences has ng-slider ? because i receive TypeError: Object [object Object] has no method 'offset'

**Comment by miculprogramator** [comment]
nop, do not work, the issue is here "var f=d.offset(this.domNode)".

**Comment by darul75** [comment]
Ok I check it asap. Fiddler is on readme fiest page if you can reproduce it. I will check on my side too

**Comment by miculprogramator** [comment]
i thing this is the difference  AngularJS v1.3.1

**Comment by darul75** [comment]
"d" variable (name after minification) in your code is just an utils function, maybe injection failed but it is weird. I will look more in depth with 1.3

**Comment by darul75** [comment]
tested with 1.3 I have not seen any differences, pls use fiddle or send me code and options I can reproduce

**Comment by mariantatarau** [comment]
something is wrong in min, utils is not injected, i solved the problem in min file, is not a solution but i don't have time to test again

**Comment by darul75** [comment]
renamed 'utils' factory to 'sliderUtils'
