### ISSUE TITLE
Using slider multiplies number

### ISSUE THREAD

**Issue by ElanHasson** [darul75/ng-slider#47]
I updated angular to 1.3.8 and now the slider multiplies the value.

For example, I set min to 190,000 and max to 228,000 and any touch to the slider multiplies the current value making the number huge, and outside of the range.

**Comment by darul75** [comment]
Confirme me if you still have issue, thx

**Comment by ElanHasson** [comment]
I still have the issue.  Must be some side effect somewhere.. Odd because
that 0.20 is the only multiplication I am performing.

I'll let you know.

**Comment by darul75** [comment]
I do not see any problem here, "from" is set to 190000 and "to" to 228000 see third last slider in this fiddle : http://jsfiddle.net/g9e9n8xc/6/ help me reproduce it ;)

**Comment by ElanHasson** [comment]
Ok-- the issue was actually concatenating my numerics as strings.

parseInt() fixed it

**Comment by darul75** [comment]
good news, do you think I need to change something, was it involved by this affectation :

scope.defaultAmount+ ($scope.defaultAmount* 0.20),

**Comment by ElanHasson** [comment]
perhaps be safe and wrap $scope.defaultAmount in parseInt
