### ISSUE TITLE
Cannot read property 'vertical' of undefined

### ISSUE THREAD

**Issue by Joneser** [darul75/ng-slider#51]
Hi, I am trying to use your control however I am getting the error shown in the title.

The code I am using looks like the following-

```
<input ng-model="value" type="text" id="mySlider1" slider options="sliderOptions" />
`
        $scope.sliderOptions = {
            from: 1,
            to: 100,
            step: 1,
            dimension: " km",
            vertical: false
        };
``

**Comment by Joneser** [comment]
I get the same error even when I don't try to define my own options:

```
<input ng-model="value" type="text" id="mySlider1" slider />

**Comment by darul75** [comment]
I check to put default values for options soon, can you try version released 2.1.2 in the meantime https://github.com/darul75/ng-slider/releases/tag/2.1.2

**Comment by Joneser** [comment]
Hi darul,

Thanks for the quick reply but I still get that problem with 2.1.2

I'll wait for the update, thanks again,
David

**Comment by Joneser** [comment]
Hi, I have it working locally now but for some reason I needed to add the options object inline as it didn't seem to pick up my options variable:

<input ng-model="value" type="text" id="mySlider1" slider options="{
                from: 1,
                to: 100,
                step: 1,
                dimension: 'km',
                vertical: false,
                css: {
                    background: {'background-color': 'silver'},
                    before: {'background-color': 'purple'},
                    default: {'background-color': 'white'},
                    after: {'background-color': 'green'},
                    pointer: {'background-color': 'red'}
                }
            }" />

**Comment by darul75** [comment]
ok I am patching it right now

**Comment by darul75** [comment]
no options will throw error, inline variable can be used now in 2.1.3
