### ISSUE TITLE
Incorrect overlap on upper limit and displayed value

### ISSUE THREAD

**Issue by j-w-miller** [darul75/ng-slider#52]
When the slider is mover to the lower range, it's displayed value overlaps nicely with the lower limit of the slider.  This does not occur on the upper limit, seemingly because the upper limit value is positioned towards the inside of the slider. A simple but non-elegant fix may be to position the upper limit to the right of the end of the slider.  Hope this helps, thanks for the software.

**Comment by darul75** [comment]
yes indeed see what can be done, thx

**Comment by j-w-miller** [comment]
Still thinking about it ...  perhaps the current value could swap sides after it passes the middle of the slider.  that might be a cleaner solution.  regards

**Comment by darul75** [comment]
I see where it comes from but could you send me one or too screenshots, thx

**Comment by j-w-miller** [comment]
![image](https://cloud.githubusercontent.com/assets/7314491/5746733/aba1dcfe-9bff-11e4-82f2-1b8d979b2d91.png)

![image](https://cloud.githubusercontent.com/assets/7314491/5746749/e5620568-9bff-11e4-858a-b044fd8952ad.png)

regards

**Comment by j-w-miller** [comment]
opps wrong button

**Comment by darul75** [comment]
will be fixed today normally for both horizontal or vertical sliders, I keep you in touch
