### ISSUE TITLE
step not working for decimal values

### ISSUE THREAD

**Issue by medaamarnadh** [darul75/ng-slider#55]
Hi,

I want a slider with fallowing options

from :0,
to:1,
step:0.5
 When i am trying to give above options slider working with 3 points that is fine.
 But the values which is shows on the points either 0 or 1 but not 0.5 at the time middle level point . 
 Same thing happening in the callback also

**Comment by darul75** [comment]
hi @medaamarnadh 

just add option attribute "round" like that:

```json
{
"from": 1,
"to": 100,
"step":0.5,
"round": 2
....
}
````
