### ISSUE TITLE
Updating a ng-model, while the slider is being moved

### ISSUE THREAD

**Issue by primez** [darul75/ng-slider#58]
Hi, Julien!
Is it possible to update the ng-model value on each slider's step, like this tooltip (http://take.ms/JSkLh) is updated?
Thank you in advance!

**Comment by darul75** [comment]
Hi @primez do you mean to get ng-model changing on every moves, I will see if it is not triggering too much events.

**Comment by primez** [comment]
Yes, update it on every move.
Thank you.

**Comment by primez** [comment]
Hi, Julien!
Have you succeeded with checking of this feature?

**Comment by darul75** [comment]
Hi sorry but i am not at home for still one week..really sorry

**Comment by darul75** [comment]
It will be done, certainly by options attribute, something like "realtime"

**Comment by primez** [comment]
Awesome! Thank you very much!

**Comment by darul75** [comment]
made few changes today but not yet for you, coming soon

**Comment by darul75** [comment]
done, put in options `realtime` attribute to true

https://github.com/darul75/ng-slider/releases/tag/2.1.8

**Comment by primez** [comment]
Cool. Thank you!

**Comment by FlavorScape** [comment]
+1 great feature. using this to control audio. I'll send you the project when it's ready for the public

**Comment by vance** [comment]
+1 great feature. I'm using this to control audio. I'll send you the project when ready for public release.

**Comment by darul75** [comment]
Ok, nice
