### ISSUE TITLE
Binding the "from" and "to" bounds of the slider

### ISSUE THREAD

**Issue by pbruneau** [darul75/ng-slider#60]
Hi all,

Currently, the data binding takes place for the ng-model attribute, but not for properties of the options attribute - i.e., referring to your "single value" example on github pages, if $scope.options.to is modified later on, the changes won't be reflected on the input component - am I right?

If so, is such a feature under consideration? Or someone might have a pretty straightforward workaround?

Thanks by advance!

**Comment by darul75** [comment]
hi @pbruneau 

you can change dynamically options and see slider updated, scale ... check demo here in source directory, just open it

https://github.com/darul75/ng-slider/blob/master/src/ng-slider.html

**Comment by pbruneau** [comment]
OK, I know where I got it wrong : with reference to your code, I was attempting to use:

    $scope.options.to = myVar;

i.e. I was assuming your lib was "deep-watching" the options object. Fixed now, I guess the issue is closed.

**Comment by mjanderson235** [comment]
I've been having the same problem.  I can play with the jsFiddle page you provided (http://jsfiddle.net/darul75/g9e9n8xc/), just adding in a button with an ng-change to use the changeOptions() function, and everything works fine.

However, when I try to get my options from a service, things go wrong. I'm calling the service within an ng-repeat, so I need separate options for each slider.  I'll change the to and from options, and the console log shows that they have been changed.  When I change the position on the slider, the callback function tells me that the to and from values have still changed to the new values - but the display still shows the original values, the pointer still behaves according to the original values, and the to and from reset to the original values immediately upon changing the slider.

(Working on getting a JSFiddle up that reproduces the problem.  It currently doesn't want to misbehave for me appropriately.)

**Comment by mjanderson235** [comment]
This is at least similar to what I'm doing.  In fact, the only real difference I can find is that the Fiddle works when my page does not.  But for the sake of illustrating what I'm trying to do:
http://jsfiddle.net/g9e9n8xc/47/

**Comment by mjanderson235** [comment]
Here's a JSFiddle for the problem:
http://jsfiddle.net/mjanderson235/g9e9n8xc/52/

**Comment by darul75** [comment]
hi, sorry I can not look deeply, I have just changed behaviour here http://jsfiddle.net/g9e9n8xc/53/

**Comment by mjanderson235** [comment]
Yeah, I realized after submitting the comment that I had accidentally gone back to the old way of trying to change the scale.  The JSFiddle works when you swap out the options like in your example, but the web page on my server still does not.

**Comment by darul75** [comment]
I try to reproduce it when I got time and be back home

**Comment by darul75** [comment]
as for options object it looks fine, now watch is made by value and not just by reference so it will works, coming in 2.1.9 version

**Comment by darul75** [comment]
https://github.com/darul75/ng-slider/releases/tag/2.1.9
