### ISSUE TITLE
When selecting a range, expand the range when the user clicks outside it

### ISSUE THREAD

**Issue by cheriot** [darul75/ng-slider#62]
1. Start with the  "Double value" section of the [demo page](http://darul75.github.io/ng-slider/). It has $10 - $15 selected.
2. Click on $5. It will expand the low end of the range to that number. Awesome.
3. Click on $25. It will again try to move the low end of the range resulting in both low and high being $15. Instead, it should move the high side of the range to $25 and leave the low unchanged.

Great library, I think this is a small way to improve it. I'll poke around and see if I can find the code that controls this.

**Comment by darul75** [comment]
Yes I know this case but thank you to open it as we need this behaviour. Will do it in few week, not at home right now. You will see a clock handler in code then need to get right pointer to move it.

**Comment by darul75** [comment]
hi, can you check if current version fits you request, thx https://github.com/darul75/ng-slider/releases/tag/2.1.7
