### ISSUE TITLE
Lables are not moving when we click outside the range

### ISSUE THREAD

**Issue by divyamohan** [darul75/ng-slider#63]
Hi,
The to label is not moving when we click outside the to range

**Comment by darul75** [comment]
Yes I have seen it ;) damn...

**Comment by divyamohan** [comment]
Also can we give string values for the slider?

**Comment by darul75** [comment]
sure, some examples here https://github.com/darul75/ng-slider/blob/master/src/ng-slider.html#L112

**Comment by divyamohan** [comment]
i mean to show steps instead of numbers in slider labels. I did see a solution for jquery slider.
http://stackoverflow.com/questions/11339601/jquery-ui-slider-with-string-values

**Comment by darul75** [comment]
Sure, good idea, i just need time as few bug to resolve first. I will open other issue and keep you in touch.

**Comment by darul75** [comment]
it was tricky, thx for testing following version https://github.com/darul75/ng-slider/releases/tag/2.1.8
and put any star if you can on repo ;)

**Comment by darul75** [comment]
and for your scale labels, just put it like that in you options

`scale` attribute options:

```json
$scope.options = {				
 from: 0,
to: 80,
step: 1,
scale: ['very sad', 'sad', 'not so sad', 'happy', 'very happy']									
};
```

**Comment by divyamohan** [comment]
:-) Thanks for fixing this bug. This slider is really useful and i was looking for an angular slider with no jquery dependency.
Please let me know how you calculate the label distance. Because i am looking for the label to be separated. After this fix just noticed that on load they are together separeted by -

**Comment by darul75** [comment]
I will update to get separator - only when labels to closed, sorry

**Comment by darul75** [comment]
https://github.com/darul75/ng-slider/releases/tag/2.1.9

**Comment by praswebdev** [comment]
Thanks a lot..works perfect
