### ISSUE TITLE
ng-disabled has no effect

### ISSUE THREAD

**Issue by kehoej** [darul75/ng-slider#64]
ng-disabled has no effect

**Comment by darul75** [comment]
well, attribute changes are watched but not initial value, sorry I have to fix it.

here in demo it works, in src dir, I need make some few changes, thx

https://github.com/darul75/ng-slider/blob/master/src/ng-slider.html#L138

**Comment by darul75** [comment]
fix in https://github.com/darul75/ng-slider/releases/tag/2.1.8

put any star on repo if you can ;)
