### ISSUE TITLE
ng-show breaks label calculations

### ISSUE THREAD

**Issue by j-w-miller** [darul75/ng-slider#67]
Hello Julien,
Came up with another issue. If the slider is wrapped with ng-hide/ng-show, then the slider is moved, the label will be displayed incorrectly.  See the following based on your jsfiddle;

http://jsfiddle.net/8nb7xcr2/

Thanks,
John

**Comment by darul75** [comment]
nice one I like ;)

**Comment by darul75** [comment]
will be available tonight or tomorrow, I keep you in touch

**Comment by kehoej** [comment]
I'm seeing this issue also.
![image](https://cloud.githubusercontent.com/assets/6454369/6234346/d47846a8-b69f-11e4-8e5a-82e49d620751.png)

**Comment by j-w-miller** [comment]
True enough

http://jsfiddle.net/5dv10xrg/

**Comment by darul75** [comment]
well it is weird, I was trying to fix it but size are not defined or zero when slider not displayed...I have done some few changes, so glad to hear it works.
I would like to put a list or websites using ng-slider what do you think ? it your online or corporate one or mobile app maybe ;) ?

**Comment by j-w-miller** [comment]
Yeah, I saw that (re size=0).  Makes sense when it hidden, but would think it'd be updated to the proper size when displayed. Angular voodoo.  Re websites, let me chat with my manager and I'll get back with you.  regards.

**Comment by j-w-miller** [comment]
Sent an email to darul75@gmail.com regarding list of websites
