### ISSUE TITLE
Initial value doesn't show when from is greater than to.

### ISSUE THREAD

**Issue by tandyjames** [darul75/ng-slider#68]
http://jsfiddle.net/g9e9n8xc/62/

If you read the value after it first starts, it shows the correct numbers "100;1", but the graphic doesn't match. If you set the value different then back (either via ui or in code) then it displays correctly.

Thanks,
T.J.

**Comment by scchadwi** [comment]
+1

**Comment by dafrautn** [comment]
+1

**Comment by darul75** [comment]
hi all,
I understand this is a bug but can not figure where ;)
Do you mean label should show "100-1" and not only "1" ?
thx

**Comment by tandyjames** [comment]
The slider should be blue with a ball at the top (100) and at the bottom (1).
Instead it is grey and both balls are at the bottom.

**Comment by tandyjames** [comment]
It might help if I had a non minimized version. How do I use it non minimized (the dist dir only has a .min).

**Comment by darul75** [comment]
ooh yeah sure there is a bug, you can find src not minified in src folder and html, I will fix it soon

**Comment by darul75** [comment]
done, will be available tonight or tomorrow

**Comment by darul75** [comment]
new release, tell me if it is ok https://github.com/darul75/ng-slider/releases/tag/2.2.0

**Comment by tandyjames** [comment]
Perfect!!! Thanks!

**Comment by scchadwi** [comment]
Thanks for the fix!  This works now as expected.
