### ISSUE TITLE
stop the slider drag

### ISSUE THREAD

**Issue by praswebdev** [darul75/ng-slider#69]
Can I stop the dual slider drag, when they are one step apart

**Comment by darul75** [comment]
I guess yes but I do not undersand, can you send a screenshot or details.
thx

**Comment by praswebdev** [comment]
Right now both pointers overlap and it won't allow u to drag further. That is when the difference is zero. Can i customize this feature. That is stop them when the difference is one and then do not allow the slider to dry further.

**Comment by darul75** [comment]
understood, very nice idea, I will implement a minimum gap feature to fix it.

**Comment by darul75** [comment]
new release, tell me if it is ok https://github.com/darul75/ng-slider/releases/tag/2.2.0

just put "threshold" option attribute to "1" or "5" for instance to force minimum gap between pointers

**Comment by praswebdev** [comment]
working good :-) ..thanks
