### ISSUE TITLE
Value (above slider) displays incorrectly if slider is initially hidden

### ISSUE THREAD

**Issue by Drosco** [darul75/ng-slider#70]
Great slider. After toggling visibility, move the slider.  The value will jump to the right.  

http://jsfiddle.net/am4f7qhs/

**Comment by darul75** [comment]
last version 2.2.0 fix issue http://jsfiddle.net/darul75/am4f7qhs/1/

**Comment by Drosco** [comment]
Thank you!  Fixed in 13 minutes.  Impressive.

**Comment by Drosco** [comment]
Right now there is an initial value indicator that is preserved if the slider is moved to the right of the initial value.  This indicator is lost if moved to the left.  Anyway to preserve it?

**Comment by darul75** [comment]
second one is issue, I check asap ;)

**Comment by Drosco** [comment]
Thanks again.  I do think the initial value is useful.  But even better would be the ability to set a default value that could vary from the initial value.  That way, when they return to the "web page" they could see their current value and what the default value is. I'm setting a default value know using the scale you provided.  [0, 'Default', 50, 75, 100], but this is awkward for numbers such as 2.76.

**Comment by Drosco** [comment]
Another way to handle it with your slider is to set the model to the default value and than change the model value with an offset value.

**Comment by Drosco** [comment]
Using this in the options preserves the initial default setting - even if you move to a lower value.

css: {
          default: {"background-color": "white"},
        }

**Comment by darul75** [comment]
fix for color is done, ability to set an offset default value will be put in another issue, thx for all details

**Comment by Drosco** [comment]
Thanks Julien,
I appreciate your efforts.

John Andraschko
