### ISSUE TITLE
2 value slider - the min slider leaves a default indicator but the max slider does not.

### ISSUE THREAD

**Issue by Drosco** [darul75/ng-slider#73]
![image](https://cloud.githubusercontent.com/assets/11159930/6379193/0df4dd72-bcf6-11e4-8cbc-2f0f56a58683.png)

See attached image.

**Comment by darul75** [comment]
oh yeah sorry, bad testing, fix it soon

**Comment by darul75** [comment]
ok for you here ?
http://jsfiddle.net/darul75/6n7sa5kb/

**Comment by Drosco** [comment]
Julien,
The slider is working correctly.  However, I wanted  the default indicator for both the min and max.  Now it is gone for both.



John Andraschko

**Comment by darul75** [comment]
hmm oki sorry I was thinking about it I fix it ;)

**Comment by darul75** [comment]
can you check again and tell me if it fits the need, thx

**Comment by Drosco** [comment]
That is beautiful.

Yes – fixed.

I’ve been using your slider a lot.  Let me know what type of write up (information) I could provide you to help you out.



John Andraschko

**Comment by darul75** [comment]
I was thinking of any websites list using it if you have.

But your bug reports are very very useful, I appreciate.

**Comment by Drosco** [comment]
We are not in production yet.  But I’ll let you know when so.

Here is your slider in action.  It is doing everything I need.

[cid:image001.png@01D051B9.99A5BD80]








John Andraschko

**Comment by darul75** [comment]
release 2.2.2 ready for you

**Comment by Drosco** [comment]
Ok – thanks.

John Andraschko
