### ISSUE TITLE
Slider display value doesn't match model

### ISSUE THREAD

**Issue by Drosco** [darul75/ng-slider#76]
http://jsfiddle.net/Lbcyx5of/

![image](https://cloud.githubusercontent.com/assets/11159930/6491443/d1f8efc0-c272-11e4-8ebd-933fc97d8a46.png)

Wondering how to handle.  
-tried several values for round. 
-Perhaps .001 (thousands not supported)
-Math.ceiling()
...

**Comment by darul75** [comment]
I check what can be done

**Comment by darul75** [comment]
Gonna be hard, browsers have different way of rounding, 3 digits floating numbers is too much to play with pixels...I got no real solution

**Comment by Drosco** [comment]
No worries.

It really doesn’t make sense to use that small of scale in a slider anyway.



John Andraschko
