### ISSUE TITLE
OnMouseUp event doesn't fire when slider is in "realtime" mode

### ISSUE THREAD

**Issue by nagey** [darul75/ng-slider#77]
the mouseup event won't fire, but the mousemove will. it would be good to get a "final" result of the change or something like that, so that you can act if the user is actively changing the slider, or they're released it.

granted, you can hook on top of this, but would be nice if the directive would give it to you straight.

**Comment by darul75** [comment]
hi, I have added a `released` parameter passed to callback function

```javascript
$scope.options = {				
	to: 100,
        from: 1,
        step: 1,
        dimension: " km",            
        realtime: true,
	callback: function(value, released) {
           // released true when mouse is up
	}		
};
```

will it fit your need ?

**Comment by nagey** [comment]
yes. this is perfect. thank you!

**Comment by darul75** [comment]
Ok but let's wait for release I keep you in touch when done in vacation right now ;)

**Comment by darul75** [comment]
https://github.com/darul75/ng-slider/releases/tag/2.2.3
