### ISSUE TITLE
Styling through css

### ISSUE THREAD

**Issue by y-lohse** [darul75/ng-slider#81]
Hi,
thanks for the work, dropping ng-slider in an existing project worked very well! The only problems I have are related to styling:

- having to specify css colors inside the options (so through javascript) is really not great. I'd like to keep my color codes in my css. I think it could be as trivial as exposing class names for the before/after/range elements?
- the default css is very oppinionated, for example setting a font family. Adjusting sizes (for labels or handles for example) also doesn't paly too nicely by default.

So yeah, if there are any plans for future versions, giving css some love would be great :-)

**Comment by darul75** [comment]
yes indeed, css are not relatively trivials and should be rewritten, this week someone has made a PR to play little bit more with css, but it involves js, I will certainly merge it first and clean css thenhttps://github.com/darul75/ng-slider/pull/80

**Comment by darul75** [comment]
I created a branch and is working on it, I try to simplify original css but it will take little time to be finished, I keep you in touch.

**Comment by y-lohse** [comment]
Great, let me know if I can help with anything :-)
