### ISSUE TITLE
IE9

### ISSUE THREAD

**Issue by olegakbarov** [darul75/ng-slider#83]
Seems like doesn't support IE9, does it?

**Comment by darul75** [comment]
I do not know this browser does it really exist  ? 

https://github.com/darul75/ng-slider/issues/56

I have not tested yet this comment

```
looks like you are using pageX and pageY which is not defined in IE8. 
Used clientX and cientY, if pageX is undefined and worked in IE8
```

**Comment by olegakbarov** [comment]
Yeah, it does exists. Unfortunately.
But i have no idea what could possibly be wrong.

**Comment by darul75** [comment]
here fine with version 9.0.8112.16421

check by pressing F12 "Browser mode" and "Document mode"

**Comment by olegakbarov** [comment]
After a few hours of frustration it turned out that you need to remove `console.log`'s from the code
I almost was ready to reimplement the whole thing in jQuery  :<

**Comment by olegakbarov** [comment]
i guess you can mark it as solved!

**Comment by darul75** [comment]
jQuery ;) oh no ;)  thx I will check console.log

**Comment by olegakbarov** [comment]
nevermind, i had all `console.log`'s in my own code so the directive is clear

**Comment by darul75** [comment]
ok thx for feedback do not hesitate, cleaning css I will then include your first idea for labels into

**Comment by olegakbarov** [comment]
Awesome! I'll take a look into source code at this weekend and maybe will be able to help you out
