### ISSUE TITLE
Cannot move slider once maximum is set in double value slider

### ISSUE THREAD

**Issue by sandeeppbajaj** [darul75/ng-slider#84]
Choose to use the double value slider, you can bring both markers to minimum value and then change again; it works. 
On the other hand, if you bring both the markers on maximum value and then change again; it doesn't work.

In the demo page (http://darul75.github.io/ng-slider/), for double value example select min and max as $40

**Comment by darul75** [comment]
Hi,

can you update this fiddle with you case http://jsfiddle.net/darul75/g9e9n8xc/

thx

**Comment by sandeeppbajaj** [comment]
Hi,

Please refer the updated fiddle: http://jsfiddle.net/g9e9n8xc/77/

Thank you.

**Comment by darul75** [comment]
sorry not get time but I fix it asap

**Comment by darul75** [comment]
available https://github.com/darul75/ng-slider/releases/tag/2.2.4

**Comment by sandeeppbajaj** [comment]
Works fine...thank you for the fix. Very useful component.

**Comment by darul75** [comment]
Glad to hear it thx, but it has taken me too much of my times often...:)
